Fixes MultisiteSiteDoesNotExist running effect_consent 0022
error: `multisite.exceptions.MultisiteSiteDoesNotExist: Site matching
query does not exist. Got site_id=1.`